# fly.toml app configuration file generated for c64-diagnostic on 2023-11-09T12:19:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "c64-diagnostic"
primary_region = "mia"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
